name: Build & Deploy
on:
  push:
   branches: [master]
   
jobs:
  deploy:
     runs-on: ubuntu-latest
     steps:
      - uses: appleboy/ssh-action@master
        name: executing remote ssh commands using password
        with:
         host: ${{secrets.SSH_HOST}}
         key: ${{secrets.SSH_KEY}}
         username: ${{secrets.SSH_USERNAME}}

         script: |
          mkdir test  --present
          cd test
          git clone git@github.com:aannkur/nodetest.git
          cd nodetest
             - run: npm install
             - run: npm install pm2 -g
             - run: pm2 start Index.js

